# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieList-RXSWIFT' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieList-RXSWIFT
  #pod 'RxCocoa',    '~> 2.0'
  pod 'RxSwift',    '~> 2.0'
  pod 'RxCocoa',    '~> 2.0'


  target 'MovieList-RXSWIFTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieList-RXSWIFTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
