# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BackgroundChangeMVVM' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "RxSwift"
pod "RxCocoa"
pod "ChameleonFramework"
  # Pods for BackgroundChangeMVVM

  target 'BackgroundChangeMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BackgroundChangeMVVMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
