# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherMVVM' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'Alamofire', '~> 3.4'
  # Pods for WeatherMVVM

  target 'WeatherMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherMVVMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
