# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveSwift-Revised' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveSwift-Revised
 # pod 'RxCocoa',    '~> 2.0'
    pod 'RxSwift',    '~> 2.0'
    pod 'RxCocoa',    '~> 2.0'

  target 'ReactiveSwift-RevisedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveSwift-RevisedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
