# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'rxswiftexample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for rxswiftexample

  target 'rxswiftexampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rxswiftexampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
