# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'


target 'NetworkCallingProject' do

pod 'Alamofire'



  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkCallingProject

  target 'NetworkCallingProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkCallingProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
