# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'RXSWIFTEXAMPLES' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '~> 2.0'
  pod 'RxCocoa',    '~> 2.0'
  # Pods for RXSWIFTEXAMPLES

  target 'RXSWIFTEXAMPLESTests' do


#//    inherit! :search_paths
    # Pods for testing
  end

  target 'RXSWIFTEXAMPLESUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
