# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RXsWIFTEXamplENEW' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RXsWIFTEXamplENEW
pod 'RxSwift'
pod 'RxCocoa'

  target 'RXsWIFTEXamplENEWTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RXsWIFTEXamplENEWUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
